# fly.toml app configuration file generated for hmy3743-chat on 2023-05-10T10:58:00+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hmy3743-chat"
primary_region = "nrt"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "hmy3743-chat.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
